branch1-change2
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DualListDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DUALLISTDEMO_DIALOG         102
#define CG_IDS_TIPOFTHEDAY              104
#define CG_IDS_TIPOFTHEDAYMENU          105
#define CG_IDS_DIDYOUKNOW               106
#define CG_IDS_FILE_ABSENT              107
#define CG_IDP_FILE_CORRUPT             108
#define CG_IDS_TIPOFTHEDAYHELP          109
#define IDB_LIGHTBULB                   112
#define IDD_TIP                         113
#define IDR_MAINFRAME                   128
#define IDD_SELECTIONDLG                129
#define IDB_TICKER_DRAGBAR              129
#define IDD_SELL                        130
#define IDB_TICKER_BKG                  130
#define IDD_BUY                         131
#define IDD_BANK_JIAOYI                 132
#define IDD_ENTER_BANK                  133
#define IDI_HISPITAL                    134
#define IDD_IN_HISPITAL                 135
#define IDD_REPLAY_LOAD                 136
#define IDD_TOP_PLAYER                  137
#define IDD_NEWS                        138
#define IDB_NEWS                        140
#define IDB_RiJI                        141
#define IDD_RIJI                        142
#define IDB_EMAIL                       144
#define IDD_NETWORK_CLUB                145
#define IDI_MONEY                       146
#define IDR_MENU                        159
#define IDD_WANGBA                      160
#define IDI_HAND1                       161
#define IDI_HAND2                       162
#define IDD_HOUSE_DLG                   163
#define IDI_HOUSE1                      163
#define IDI_CROSS                       164
#define IDD_TOP_10                      164
#define IDI_HAND3                       165
#define IDD_SETUP                       165
#define IDI_HAND4                       166
#define IDD_STORY                       166
#define IDI_HAND5                       167
#define IDD_DIALOG1                     167
#define IDI_HAND6                       168
#define IDD_BOSS_COME                   168
#define IDI_HAND7                       169
#define IDI_HAND8                       170
#define IDB_BG                          170
#define IDI_HAND9                       171
#define IDD_POST_MONEY                  171
#define IDD_SHENGMING                   172
#define IDB_LOGO                        173
#define IDC_SELECTIONDLG                1000
#define IDC_LIST1                       1001
#define IDC_LIST2                       1002
#define IDC_REMOVE                      1003
#define IDC_TIPSTRING                   1003
#define IDC_ADDALL                      1004
#define IDC_REMOVEALL                   1005
#define IDC_ADD                         1006
#define IDC_LOC_JIANGUOMEN              1008
#define IDC_LOC_XIZHIMEN                1009
#define IDC_LOC_GONGZHUFEN              1010
#define IDC_LOC_BEIJINGZHAN             1011
#define IDC_TOP_MESSAGE                 1012
#define IDC_LOC_FUXINGMEN               1013
#define IDC_LOC_CHONGWENMEN             1014
#define IDC_LOC_PINGGUOYUAN             1015
#define IDC_LOC_DONGZHIMEN              1016
#define IDC_LOC_JISHUITAN               1017
#define IDC_GOTO_BANK                   1018
#define IDC_CASH                        1020
#define IDC_LOAD                        1021
#define IDC_BUY_CASH                    1022
#define IDC_BUY_COUNT                   1023
#define IDC_ABOUT_ME                    1025
#define IDC_HIGH_SCORE                  1026
#define IDC_SELL_MSG                    1027
#define IDC_SELL_COUNT                  1028
#define IDC_AUTHOR                      1029
#define IDC_POSTOFFICE                  1030
#define IDC_HOSPITAL                    1031
#define IDC_LOC_CHANGCHUNJIE            1032
#define IDC_BANK_MONEY                  1035
#define IDC_NETWORK                     1036
#define IDC_SAVE_QUIT_MSG               1037
#define IDC_MONEY_CNT                   1038
#define IDC_SPIN1                       1039
#define IDC_BANK_GREETING               1040
#define IDC_HISPITAL_MSG                1041
#define IDC_CURE_POINT                  1042
#define IDC_LOAD_MSG                    1043
#define IDC_REPLAY_LOAD_CNT             1044
#define IDC_TOP_PLAYER_LIST             1045
#define IDC_NAME                        1046
#define IDC_STATIC_COUNTER              1047
#define IDC_STATIC_FAME                 1048
#define IDC_MY_DEBT_LED                 1050
#define IDC_STATIC1                     1051
#define IDC_MSG                         1052
#define IDC_EDIT1                       1053
#define IDC_PING                        1054
#define IDC_GONGZHU                     1055
#define IDC_MAIL_ME                     1074
#define IDC_TRY                         1084
#define IDC_HOSP                        1085
#define IDC_POST                        1086
#define IDC_AGENCY                      1087
#define IDC_WANGBA                      1088
#define IDC_SAY1                        1089
#define IDC_BOSS                        1089
#define IDC_SAY2                        1090
#define IDC_GO_SHANGHAI                 1090
#define IDC_RICH_MSG                    1091
#define IDC_MY_NAME                     1092
#define IDC_FREE_GAME                   1095
#define IDC_GAME_DEV                    1096
#define IDC_GUO_EMAIL                   1097
#define IDC_CLOSE_SOUND                 1098
#define IDC_FAME_GET                    1099
#define IDC_HACKER                      1100
#define IDC_GUO_GROUPS                  1101
#define IDC_GROUPS                      1102
#define IDC_ZAOBAO1                     1103
#define IDC_SOHU1                       1104
#define IDC_NO_HOUSE                    1107
#define IDC_WUPING                      1108
#define IDC_H_M_1                       1109
#define IDC_H_M_2                       1110
#define IDC_QUIT                        1111
#define IDC_INIT_MSG                    1112
#define IDC_BUTTON1                     1114
#define IDC_SPELL_CHECK                 1115
#define IDC_BG                          1116
#define IDC_LOC                         1120
#define IDC_POST_MONEY                  1121
#define IDC_DECLARE                     1122
#define IDC_LOGO                        1123
#define ST_FOOTER                       1264
#define IDB_MORE                        1266
#define ST_HEADER                       1267
#define IDC_STARTUP                     2001
#define IDC_NEXTTIP                     2002
#define IDC_TIP_RECT                    2004
#define ID_INTRO                        32771
#define ID_HIGH                         32773
#define ID_EXIT_ME                      32774
#define IDM_BANK                        32775
#define IDM_POSTOFFICE                  32776
#define IDM_HOSPIAL                     32777
#define IDM_HOUSE_AGENT                 32778
#define IDM_AIRPORT                     32779
#define IDM_WANGBA                      32780
#define ID_ABOUT                        32781
#define IDM_NEW_GAME                    32782
#define IDM_SETUP                       32783
#define IDC_STORY                       32784
#define IDC_BEIJING_INTRO               32785

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
